# Generated by Django 3.2.5 on 2021-11-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('reg_no', models.AutoField(primary_key=True, serialize=False)),
                ('counter', models.CharField(choices=[('counter1', 'counter 1'), ('counter2', 'counter 2'), ('counter3', 'counter 3'), ('counter4', 'counter 4'), ('counter5', 'counter 5')], default='counter1', max_length=9)),
                ('service', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
