# Generated by Django 3.2.5 on 2021-11-11 02:30

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=False, verbose_name=django.db.models.fields.AutoField),
        ),
    ]
